// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppKeyExists():Promise<boolean>;

export function AppPrivateKeyPath():Promise<string>;

export function BrowseFile(arg1:string,arg2:string):Promise<string>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function GenerateAppKey():Promise<string>;

export function IsTunnelRunning():Promise<boolean>;

export function LoadConfig():Promise<main.AppSettings>;

export function LoadPublicKey():Promise<string>;

export function P2PAcceptAnswer(arg1:string):Promise<string>;

export function P2PGenerateOffer(arg1:string):Promise<string>;

export function P2PIsActive():Promise<boolean>;

export function P2PProvideAnswer(arg1:string):Promise<string>;

export function P2PStop():Promise<void>;

export function SaveConfig(arg1:main.AppSettings):Promise<void>;

export function StartTunnel(arg1:main.TunnelSettings):Promise<void>;

export function StopTunnel():Promise<void>;
