// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppKeyExists() {
  return window['go']['main']['App']['AppKeyExists']();
}

export function AppPrivateKeyPath() {
  return window['go']['main']['App']['AppPrivateKeyPath']();
}

export function BrowseFile(arg1, arg2) {
  return window['go']['main']['App']['BrowseFile'](arg1, arg2);
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function GenerateAppKey() {
  return window['go']['main']['App']['GenerateAppKey']();
}

export function GetPublicIP() {
  return window['go']['main']['App']['GetPublicIP']();
}

export function IsTunnelRunning() {
  return window['go']['main']['App']['IsTunnelRunning']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function LoadPublicKey() {
  return window['go']['main']['App']['LoadPublicKey']();
}

export function P2PAcceptAnswer(arg1) {
  return window['go']['main']['App']['P2PAcceptAnswer'](arg1);
}

export function P2PGenerateOffer(arg1) {
  return window['go']['main']['App']['P2PGenerateOffer'](arg1);
}

export function P2PIsActive() {
  return window['go']['main']['App']['P2PIsActive']();
}

export function P2PProvideAnswer(arg1) {
  return window['go']['main']['App']['P2PProvideAnswer'](arg1);
}

export function P2PSetConfig(arg1) {
  return window['go']['main']['App']['P2PSetConfig'](arg1);
}

export function P2PStop() {
  return window['go']['main']['App']['P2PStop']();
}

export function RelayGetCredentials() {
  return window['go']['main']['App']['RelayGetCredentials']();
}

export function RelayIsRunning() {
  return window['go']['main']['App']['RelayIsRunning']();
}

export function RelayStart(arg1) {
  return window['go']['main']['App']['RelayStart'](arg1);
}

export function RelayStop() {
  return window['go']['main']['App']['RelayStop']();
}

export function SSHCheckKeyAuth(arg1) {
  return window['go']['main']['App']['SSHCheckKeyAuth'](arg1);
}

export function SSHSetupBusy() {
  return window['go']['main']['App']['SSHSetupBusy']();
}

export function SSHSetupCancel() {
  return window['go']['main']['App']['SSHSetupCancel']();
}

export function SSHSetupReply(arg1) {
  return window['go']['main']['App']['SSHSetupReply'](arg1);
}

export function SSHSetupStart(arg1) {
  return window['go']['main']['App']['SSHSetupStart'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function StartTunnel(arg1) {
  return window['go']['main']['App']['StartTunnel'](arg1);
}

export function StopTunnel() {
  return window['go']['main']['App']['StopTunnel']();
}
